/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedMediaIndexRouteImport } from './routes/_authenticated/media/index'
import { Route as AuthenticatedMediaAddRouteImport } from './routes/_authenticated/media/add'
import { Route as AuthenticatedMediaViewIdRouteImport } from './routes/_authenticated/media/view.$id'
import { Route as AuthenticatedMediaUpdateIdRouteImport } from './routes/_authenticated/media/update.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMediaIndexRoute = AuthenticatedMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaAddRoute = AuthenticatedMediaAddRouteImport.update({
  id: '/media/add',
  path: '/media/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaViewIdRoute =
  AuthenticatedMediaViewIdRouteImport.update({
    id: '/media/view/$id',
    path: '/media/view/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaUpdateIdRoute =
  AuthenticatedMediaUpdateIdRouteImport.update({
    id: '/media/update/$id',
    path: '/media/update/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/media/add': typeof AuthenticatedMediaAddRoute
  '/media/': typeof AuthenticatedMediaIndexRoute
  '/media/update/$id': typeof AuthenticatedMediaUpdateIdRoute
  '/media/view/$id': typeof AuthenticatedMediaViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/media/add': typeof AuthenticatedMediaAddRoute
  '/media': typeof AuthenticatedMediaIndexRoute
  '/media/update/$id': typeof AuthenticatedMediaUpdateIdRoute
  '/media/view/$id': typeof AuthenticatedMediaViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/media/add': typeof AuthenticatedMediaAddRoute
  '/_authenticated/media/': typeof AuthenticatedMediaIndexRoute
  '/_authenticated/media/update/$id': typeof AuthenticatedMediaUpdateIdRoute
  '/_authenticated/media/view/$id': typeof AuthenticatedMediaViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/media/add'
    | '/media/'
    | '/media/update/$id'
    | '/media/view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/media/add'
    | '/media'
    | '/media/update/$id'
    | '/media/view/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/media/add'
    | '/_authenticated/media/'
    | '/_authenticated/media/update/$id'
    | '/_authenticated/media/view/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/media/': {
      id: '/_authenticated/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof AuthenticatedMediaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media/add': {
      id: '/_authenticated/media/add'
      path: '/media/add'
      fullPath: '/media/add'
      preLoaderRoute: typeof AuthenticatedMediaAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media/view/$id': {
      id: '/_authenticated/media/view/$id'
      path: '/media/view/$id'
      fullPath: '/media/view/$id'
      preLoaderRoute: typeof AuthenticatedMediaViewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media/update/$id': {
      id: '/_authenticated/media/update/$id'
      path: '/media/update/$id'
      fullPath: '/media/update/$id'
      preLoaderRoute: typeof AuthenticatedMediaUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMediaAddRoute: typeof AuthenticatedMediaAddRoute
  AuthenticatedMediaIndexRoute: typeof AuthenticatedMediaIndexRoute
  AuthenticatedMediaUpdateIdRoute: typeof AuthenticatedMediaUpdateIdRoute
  AuthenticatedMediaViewIdRoute: typeof AuthenticatedMediaViewIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMediaAddRoute: AuthenticatedMediaAddRoute,
  AuthenticatedMediaIndexRoute: AuthenticatedMediaIndexRoute,
  AuthenticatedMediaUpdateIdRoute: AuthenticatedMediaUpdateIdRoute,
  AuthenticatedMediaViewIdRoute: AuthenticatedMediaViewIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
