/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedMediaIndexRouteImport } from './routes/_authenticated/media/index'
import { Route as AuthenticatedCollectionIndexRouteImport } from './routes/_authenticated/collection/index'
import { Route as AuthenticatedCollectionAddRouteImport } from './routes/_authenticated/collection/add'
import { Route as AuthenticatedMediaFormsRouteRouteImport } from './routes/_authenticated/media/_forms/route'
import { Route as AuthenticatedMediaViewIdRouteImport } from './routes/_authenticated/media/view.$id'
import { Route as AuthenticatedMediaFormsAddRouteImport } from './routes/_authenticated/media/_forms/add'
import { Route as AuthenticatedCollectionViewIdRouteImport } from './routes/_authenticated/collection/view.$id'
import { Route as AuthenticatedCollectionEditIdRouteImport } from './routes/_authenticated/collection/edit.$id'
import { Route as AuthenticatedMediaFormsUpdateIdRouteImport } from './routes/_authenticated/media/_forms/update.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaIndexRoute = AuthenticatedMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionIndexRoute =
  AuthenticatedCollectionIndexRouteImport.update({
    id: '/collection/',
    path: '/collection/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectionAddRoute =
  AuthenticatedCollectionAddRouteImport.update({
    id: '/collection/add',
    path: '/collection/add',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaFormsRouteRoute =
  AuthenticatedMediaFormsRouteRouteImport.update({
    id: '/media/_forms',
    path: '/media',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaViewIdRoute =
  AuthenticatedMediaViewIdRouteImport.update({
    id: '/media/view/$id',
    path: '/media/view/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaFormsAddRoute =
  AuthenticatedMediaFormsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AuthenticatedMediaFormsRouteRoute,
  } as any)
const AuthenticatedCollectionViewIdRoute =
  AuthenticatedCollectionViewIdRouteImport.update({
    id: '/collection/view/$id',
    path: '/collection/view/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectionEditIdRoute =
  AuthenticatedCollectionEditIdRouteImport.update({
    id: '/collection/edit/$id',
    path: '/collection/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaFormsUpdateIdRoute =
  AuthenticatedMediaFormsUpdateIdRouteImport.update({
    id: '/update/$id',
    path: '/update/$id',
    getParentRoute: () => AuthenticatedMediaFormsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/media': typeof AuthenticatedMediaFormsRouteRouteWithChildren
  '/collection/add': typeof AuthenticatedCollectionAddRoute
  '/collection/': typeof AuthenticatedCollectionIndexRoute
  '/media/': typeof AuthenticatedMediaIndexRoute
  '/collection/edit/$id': typeof AuthenticatedCollectionEditIdRoute
  '/collection/view/$id': typeof AuthenticatedCollectionViewIdRoute
  '/media/add': typeof AuthenticatedMediaFormsAddRoute
  '/media/view/$id': typeof AuthenticatedMediaViewIdRoute
  '/media/update/$id': typeof AuthenticatedMediaFormsUpdateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/media': typeof AuthenticatedMediaIndexRoute
  '/collection/add': typeof AuthenticatedCollectionAddRoute
  '/collection': typeof AuthenticatedCollectionIndexRoute
  '/collection/edit/$id': typeof AuthenticatedCollectionEditIdRoute
  '/collection/view/$id': typeof AuthenticatedCollectionViewIdRoute
  '/media/add': typeof AuthenticatedMediaFormsAddRoute
  '/media/view/$id': typeof AuthenticatedMediaViewIdRoute
  '/media/update/$id': typeof AuthenticatedMediaFormsUpdateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/media/_forms': typeof AuthenticatedMediaFormsRouteRouteWithChildren
  '/_authenticated/collection/add': typeof AuthenticatedCollectionAddRoute
  '/_authenticated/collection/': typeof AuthenticatedCollectionIndexRoute
  '/_authenticated/media/': typeof AuthenticatedMediaIndexRoute
  '/_authenticated/collection/edit/$id': typeof AuthenticatedCollectionEditIdRoute
  '/_authenticated/collection/view/$id': typeof AuthenticatedCollectionViewIdRoute
  '/_authenticated/media/_forms/add': typeof AuthenticatedMediaFormsAddRoute
  '/_authenticated/media/view/$id': typeof AuthenticatedMediaViewIdRoute
  '/_authenticated/media/_forms/update/$id': typeof AuthenticatedMediaFormsUpdateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/media'
    | '/collection/add'
    | '/collection/'
    | '/media/'
    | '/collection/edit/$id'
    | '/collection/view/$id'
    | '/media/add'
    | '/media/view/$id'
    | '/media/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/media'
    | '/collection/add'
    | '/collection'
    | '/collection/edit/$id'
    | '/collection/view/$id'
    | '/media/add'
    | '/media/view/$id'
    | '/media/update/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/media/_forms'
    | '/_authenticated/collection/add'
    | '/_authenticated/collection/'
    | '/_authenticated/media/'
    | '/_authenticated/collection/edit/$id'
    | '/_authenticated/collection/view/$id'
    | '/_authenticated/media/_forms/add'
    | '/_authenticated/media/view/$id'
    | '/_authenticated/media/_forms/update/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media/': {
      id: '/_authenticated/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof AuthenticatedMediaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collection/': {
      id: '/_authenticated/collection/'
      path: '/collection'
      fullPath: '/collection/'
      preLoaderRoute: typeof AuthenticatedCollectionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collection/add': {
      id: '/_authenticated/collection/add'
      path: '/collection/add'
      fullPath: '/collection/add'
      preLoaderRoute: typeof AuthenticatedCollectionAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media/_forms': {
      id: '/_authenticated/media/_forms'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaFormsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media/view/$id': {
      id: '/_authenticated/media/view/$id'
      path: '/media/view/$id'
      fullPath: '/media/view/$id'
      preLoaderRoute: typeof AuthenticatedMediaViewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media/_forms/add': {
      id: '/_authenticated/media/_forms/add'
      path: '/add'
      fullPath: '/media/add'
      preLoaderRoute: typeof AuthenticatedMediaFormsAddRouteImport
      parentRoute: typeof AuthenticatedMediaFormsRouteRoute
    }
    '/_authenticated/collection/view/$id': {
      id: '/_authenticated/collection/view/$id'
      path: '/collection/view/$id'
      fullPath: '/collection/view/$id'
      preLoaderRoute: typeof AuthenticatedCollectionViewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collection/edit/$id': {
      id: '/_authenticated/collection/edit/$id'
      path: '/collection/edit/$id'
      fullPath: '/collection/edit/$id'
      preLoaderRoute: typeof AuthenticatedCollectionEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media/_forms/update/$id': {
      id: '/_authenticated/media/_forms/update/$id'
      path: '/update/$id'
      fullPath: '/media/update/$id'
      preLoaderRoute: typeof AuthenticatedMediaFormsUpdateIdRouteImport
      parentRoute: typeof AuthenticatedMediaFormsRouteRoute
    }
  }
}

interface AuthenticatedMediaFormsRouteRouteChildren {
  AuthenticatedMediaFormsAddRoute: typeof AuthenticatedMediaFormsAddRoute
  AuthenticatedMediaFormsUpdateIdRoute: typeof AuthenticatedMediaFormsUpdateIdRoute
}

const AuthenticatedMediaFormsRouteRouteChildren: AuthenticatedMediaFormsRouteRouteChildren =
  {
    AuthenticatedMediaFormsAddRoute: AuthenticatedMediaFormsAddRoute,
    AuthenticatedMediaFormsUpdateIdRoute: AuthenticatedMediaFormsUpdateIdRoute,
  }

const AuthenticatedMediaFormsRouteRouteWithChildren =
  AuthenticatedMediaFormsRouteRoute._addFileChildren(
    AuthenticatedMediaFormsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedMediaFormsRouteRoute: typeof AuthenticatedMediaFormsRouteRouteWithChildren
  AuthenticatedCollectionAddRoute: typeof AuthenticatedCollectionAddRoute
  AuthenticatedCollectionIndexRoute: typeof AuthenticatedCollectionIndexRoute
  AuthenticatedMediaIndexRoute: typeof AuthenticatedMediaIndexRoute
  AuthenticatedCollectionEditIdRoute: typeof AuthenticatedCollectionEditIdRoute
  AuthenticatedCollectionViewIdRoute: typeof AuthenticatedCollectionViewIdRoute
  AuthenticatedMediaViewIdRoute: typeof AuthenticatedMediaViewIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedMediaFormsRouteRoute:
    AuthenticatedMediaFormsRouteRouteWithChildren,
  AuthenticatedCollectionAddRoute: AuthenticatedCollectionAddRoute,
  AuthenticatedCollectionIndexRoute: AuthenticatedCollectionIndexRoute,
  AuthenticatedMediaIndexRoute: AuthenticatedMediaIndexRoute,
  AuthenticatedCollectionEditIdRoute: AuthenticatedCollectionEditIdRoute,
  AuthenticatedCollectionViewIdRoute: AuthenticatedCollectionViewIdRoute,
  AuthenticatedMediaViewIdRoute: AuthenticatedMediaViewIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
